# Generated by Django 4.0 on 2022-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='할일', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
