# Generated by Django 3.2.13 on 2022-10-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sunning_time',
            new_name='running_time',
        ),
    ]
